version: '3'

networks:
  proxy:
  site1:
  site2:

services:
  proxy:
    image: nginx:1.13-alpine
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 81:81
    networks: 
      - proxy
      - site1
      - site2
    depends_on: 
      - site1_app_1
      - site2_app_1

  site1_app_1:
    image: nginx:1.13-alpine
    volumes:
      - ./site1/index.html:/usr/share/nginx/html/index.html
    networks:
      - site1
    
  site2_app_1:
    image: nginx:1.13-alpine
    volumes:
      - ./site2/index.html:/usr/share/nginx/html/index.html
    networks:
      - site2